package handlers

import "db"

type ResponseModelEmployee struct {
	Result    bool          `json:"result"`
	Error     string        `json:"error"`
	Employees []db.Employee `json:"body"`
}

type ResponseModelOrganization struct {
	Result       bool              `json:"result"`
	Error        string            `json:"error"`
	Organization []db.Organization `json:"body"`
}

type ResponseModelUpdateAPK struct {
	Result            bool   `json:"result"`
	Error             string `json:"error"`
	NewVersionNameAPK string `json:"body"`
}

type ResponseModelToken struct {
	Result bool   `json:"result"`
	Error  string `json:"error"`
	Token  string `json:"body"`
}

type AutoGenerated struct {
	OutputType struct {
		Type string `json:"type"`
	} `json:"outputType"`
	ApkInfo struct {
		Type        string        `json:"type"`
		Splits      []interface{} `json:"splits"`
		VersionCode int           `json:"versionCode"`
		VersionName string        `json:"versionName"`
		Enabled     bool          `json:"enabled"`
		OutputFile  string        `json:"outputFile"`
		FullName    string        `json:"fullName"`
		BaseName    string        `json:"baseName"`
	} `json:"apkInfo"`
	Path       string `json:"path"`
	Properties struct {
	} `json:"properties"`
}
